version: '3.6'

services:
  db:
    build:
      context: docker/database
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql

  php:
    build:
      context: docker/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@db:${DB_PORT}/${MARIADB_DATABASE}?serverVersion=${DB_VERSION}
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/app

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - 80:80